spring:
    application:
        name: @project.name@
        version: @project.version@
    datasource:
        url: jdbc:postgresql://localhost:5432/evently
        username:
        password:
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true

    mail:
        host: smtp.gmail.com
        port: 587
        username:
        password:
        protocol: smtp
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    base64-auth-secret: xvVhTcPXTeBB7pM3wU4CVg==
